version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/gremlin-dotnet"
    schedule:
      interval: "daily"
    target-branch: "3.5-dev"
    labels:
      - ".NET"
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/gremlin-python/src/main/python"
    schedule:
      interval: "daily"
    target-branch: "3.5-dev"
    labels:
      - "python"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/gremlin-javascript/src/main/javascript/gremlin-javascript"
    schedule:
      interval: "daily"
    target-branch: "3.5-dev"
    labels:
      - "javascript"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/gremlint"
    schedule:
      interval: "daily"
    target-branch: "3.5-dev"
    labels:
      - "javascript"
      - "dependencies"