version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/gremlin-dotnet"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - ".NET"
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/gremlin-python/src/main/python"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "python"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/gremlin-javascript/src/main/javascript/gremlin-javascript"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "javascript"
      - "dependencies"
    ignore:
      - dependency-name: "prettier"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/gremlint"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "gremlint"
      - "dependencies"
    ignore:
      - dependency-name: "prettier"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-patch" ]
  - package-ecosystem: "npm"
    directory: "/docs/gremlint"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "site"
      - "dependencies"
    ignore:
      - dependency-name: "prettier"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "@types/*"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "styled-components"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "@testing-library/*"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "web-vitals"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "gh-pages"
        update-types: [ "version-update:semver-patch" ]
  - package-ecosystem: "gomod"
    directory: "/gremlin-go"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "go"
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "java"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "3.6-dev"
    labels:
      - "dependencies"
